### ISSUE TITLE
Doesn't work on my site

### ISSUE THREAD

**Issue by disassembler** [ericduran/Drupal-for-Chrome#2]
It worked on the demo site, but not on my site. I have Drupal for firebug installed, and permissions are assigned to the Developer role of which I am a member. Any troubleshooting suggestions?

Sam

**Comment by disassembler** [comment]
By downloading the source from github and packing it (version 0.6) It worked fine. Can you push 0.6 into the Chrome Store?

**Comment by ericduran** [comment]
Yea, I guess I should update it to whats on github. I'll try to do that soon.
